name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          ftp-server: ftpupload.net
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          remote-dir: /htdocs
