name: Deploy to InfinityFree

on:
  push:
    branches:
      - html  # تأكد من اسم الفرع الصحيح

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload html folder to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: ftpupload.net  # بدل ftp-server بـ server
          username: ${{ secrets.FTP_USERNAME }}  # بدل ftp-username بـ username
          password: ${{ secrets.FTP_PASSWORD }}  # بدل ftp-password بـ password
          port: 21  # أضف البورت (عادةً 21 لـ FTP)
          protocol: ftp  # اختر البروتوكول (ftp أو ftps)
          local-dir: ./html  # مجلد الملفات المحلي
          server-dir: /htdocs  # مجلد السيرفر البعيد
